/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminNewsCreatedBy } from './adminNewsCreatedBy';
import type { AdminNewsStatus } from './adminNewsStatus';
import type { AdminNewsUpdatedBy } from './adminNewsUpdatedBy';
import type { Category } from './category';
import type { Tag } from './tag';

export interface AdminNews {
  id?: string;
  title?: string;
  slug?: string;
  excerpt?: string;
  previewImage?: string;
  contentHtml?: string;
  status?: AdminNewsStatus;
  viewsCount?: number;
  /** @nullable */
  publishedAt?: string | null;
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  canonicalUrl?: string | null;
  categoryId?: string;
  category?: Category;
  tags?: Tag[];
  /** @nullable */
  createdById?: string | null;
  /** @nullable */
  createdBy?: AdminNewsCreatedBy;
  /** @nullable */
  updatedById?: string | null;
  /** @nullable */
  updatedBy?: AdminNewsUpdatedBy;
  createdAt?: string;
  updatedAt?: string;
}
