/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserRole } from './adminUserRole';

export interface AdminUser {
  id: string;
  login: string;
  name: string;
  role: AdminUserRole;
  isActive: boolean;
  /** @nullable */
  lastLoginAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
