/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AdminTagsSort = typeof GetApiV1AdminTagsSort[keyof typeof GetApiV1AdminTagsSort];


export const GetApiV1AdminTagsSort = {
  name_asc: 'name_asc',
  name_desc: 'name_desc',
  newest: 'newest',
  oldest: 'oldest',
} as const;
