/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1AdminTagsSort } from './getApiV1AdminTagsSort';

export type GetApiV1AdminTagsParams = {
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: number;
/**
 * Items per page (max 100)
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Case-insensitive search by tag name or slug
 * @maxLength 100
 */
search?: string;
/**
 * Sort order (default: name_asc)
 */
sort?: GetApiV1AdminTagsSort;
};
