/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1NewsSort = typeof GetApiV1NewsSort[keyof typeof GetApiV1NewsSort];


export const GetApiV1NewsSort = {
  newest: 'newest',
  oldest: 'oldest',
  most_read: 'most_read',
  random: 'random',
} as const;
