/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1AdminNewsStatus = typeof GetApiV1AdminNewsStatus[keyof typeof GetApiV1AdminNewsStatus];


export const GetApiV1AdminNewsStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
