/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV1NewsSort } from './getApiV1NewsSort';

export type GetApiV1NewsParams = {
page?: number;
/**
 * @maximum 100
 */
limit?: number;
/**
 * Category slug or UUID
 */
category?: string;
/**
 * Comma-separated tag slugs or UUIDs (ANY match)
 */
tags?: string;
/**
 * Search term for title/excerpt
 */
search?: string;
sort?: GetApiV1NewsSort;
};
