/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category';

export type GetApiV1Categories200 = {
  success?: boolean;
  data?: Category[];
};
