/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiV1AdminNewsIdBodyStatus } from './patchApiV1AdminNewsIdBodyStatus';

export type PatchApiV1AdminNewsIdBody = {
  title?: string;
  slug?: string;
  excerpt?: string;
  previewImage?: string;
  contentHtml?: string;
  categoryId?: string;
  tagIds?: string[];
  status?: PatchApiV1AdminNewsIdBodyStatus;
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  canonicalUrl?: string | null;
};
