/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiV1AdminNewsIdBodyStatus = typeof PatchApiV1AdminNewsIdBodyStatus[keyof typeof PatchApiV1AdminNewsIdBodyStatus];


export const PatchApiV1AdminNewsIdBodyStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
