/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */

export type PostApiV1AdminNewsBodyStatus = typeof PostApiV1AdminNewsBodyStatus[keyof typeof PostApiV1AdminNewsBodyStatus];


export const PostApiV1AdminNewsBodyStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
} as const;
