/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV1AdminNewsBodyStatus } from './postApiV1AdminNewsBodyStatus';

export type PostApiV1AdminNewsBody = {
  title: string;
  slug?: string;
  excerpt: string;
  previewImage: string;
  contentHtml: string;
  categoryId: string;
  tagIds?: string[];
  status?: PostApiV1AdminNewsBodyStatus;
  metaTitle?: string;
  metaDescription?: string;
  canonicalUrl?: string;
};
