/**
 * Generated by orval 🍺
 * Do not edit manually.
 * News Website API
 * Production-ready REST API backend for news/movie platform with role-based access control (SUPERADMIN, ADMIN) and public read-only endpoints.
 * OpenAPI spec version: 1.0.0
 */
import type { Category } from './category';
import type { PublicNewsStatus } from './publicNewsStatus';
import type { Tag } from './tag';

export interface PublicNews {
  id?: string;
  title?: string;
  slug?: string;
  excerpt?: string;
  previewImage?: string;
  contentHtml?: string;
  status?: PublicNewsStatus;
  viewsCount?: number;
  /** @nullable */
  publishedAt?: string | null;
  /** @nullable */
  metaTitle?: string | null;
  /** @nullable */
  metaDescription?: string | null;
  /** @nullable */
  canonicalUrl?: string | null;
  category?: Category;
  tags?: Tag[];
  createdAt?: string;
  updatedAt?: string;
}
